id: DB99DFF95
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-04-18T11:13:47+00:00'
last_modified: '2022-05-30T07:18:05.217073+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    c0c0:
      image_group_id: I1PD95892
      title: རོ་བསྲེག་པའི་ཆོ་ག།
      total_pages: 1464
      order: 47
      base_file: c0c0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
